package gateway

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"

	"github.com/Lazarus-AI-Research/sovereign-stack/control/internal/embeddings"
	"github.com/Lazarus-AI-Research/sovereign-stack/control/internal/models"
)

// GenerateConfig renders the LiteLLM config from the product's registries
// (design.md §2.2: generated configuration, UI never exposed). Every stable
// alias — generation models and embedding profiles — routes to the single
// runtime endpoint; remote/cloud models keep their registry-declared routes.
func GenerateConfig(path string, modelRegistry *models.Registry, profiles *embeddings.Registry) error {
	entries, err := modelRegistry.List()
	if err != nil {
		return err
	}
	profileMap, err := profiles.List()
	if err != nil {
		return err
	}

	seen := map[string]bool{}
	var modelList []map[string]any
	addRuntimeRoute := func(alias string) {
		if alias == "" || seen[alias] {
			return
		}
		seen[alias] = true
		modelList = append(modelList, map[string]any{
			"model_name": alias,
			"litellm_params": map[string]any{
				"model":    "openai/" + alias,
				"api_base": "http://sovereign-runtime:8000/v1",
				"api_key":  "os.environ/SOVEREIGN_RUNTIME_API_KEY",
			},
		})
	}

	// Product aliases always route: the generation alias plus every
	// embedding profile's served name.
	addRuntimeRoute("assistant-large")
	for _, profile := range profileMap {
		addRuntimeRoute(profile.ServedModelName)
	}
	for _, entry := range entries {
		if entry.Source != "remote" {
			continue
		}
		// Remote OpenAI-compatible models (§2.9): model field carries the
		// upstream route; credentials stay in the environment.
		if !seen[entry.ID] {
			seen[entry.ID] = true
			modelList = append(modelList, map[string]any{
				"model_name":     entry.ID,
				"litellm_params": map[string]any{"model": entry.Model},
			})
		}
	}

	config := map[string]any{
		"model_list": modelList,
		"general_settings": map[string]any{
			"master_key": "os.environ/LITELLM_MASTER_KEY",
		},
		"litellm_settings": map[string]any{
			"drop_params":     true,
			"request_timeout": 600,
		},
	}
	raw, err := yaml.Marshal(config)
	if err != nil {
		return err
	}
	header := "# Sovereign Gateway (LiteLLM) configuration — generated by Sovereign Control.\n# Do not hand-edit; regenerate via POST /api/control/v1/gateway/config/regenerate.\n"
	if err := os.WriteFile(path, append([]byte(header), raw...), 0o644); err != nil {
		return fmt.Errorf("gateway config: %w", err)
	}
	return nil
}
