package gateway

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Lazarus-AI-Research/sovereign-stack/control/internal/embeddings"
	"github.com/Lazarus-AI-Research/sovereign-stack/control/internal/models"
)

type SecretResolver interface {
	Secret(context.Context, string) (string, error)
}

// GenerateConfig renders the LiteLLM config from the product's registries
// (design.md §2.2: generated configuration, UI never exposed). Every stable
// alias routes to its owning service; remote/cloud models keep their
// registry-declared routes.
func GenerateConfig(ctx context.Context, path string, modelRegistry *models.Registry, profiles *embeddings.Registry, secrets SecretResolver) error {
	entries, err := modelRegistry.List()
	if err != nil {
		return err
	}
	profileMap, err := profiles.List()
	if err != nil {
		return err
	}

	seen := map[string]bool{}
	var modelList []map[string]any
	addOpenAIRoute := func(alias, baseURL, apiKey string) {
		if alias == "" || seen[alias] {
			return
		}
		seen[alias] = true
		modelList = append(modelList, map[string]any{
			"model_name": alias,
			"litellm_params": map[string]any{
				"model":    "openai/" + alias,
				"api_base": baseURL,
				"api_key":  apiKey,
			},
		})
	}

	// Product aliases always route: the generation alias plus every
	// embedding profile's served name.
	addOpenAIRoute("assistant-large", "http://sovereign-runtime:8000/v1", "os.environ/SOVEREIGN_RUNTIME_API_KEY")
	for _, profile := range profileMap {
		addOpenAIRoute(profile.ServedModelName, "os.environ/SOVEREIGN_EMBEDDINGS_BASE_URL", "not-required")
	}
	for _, entry := range entries {
		if entry.Source != "remote" && entry.Source != "cloud" {
			continue
		}
		if !seen[entry.ID] {
			seen[entry.ID] = true
			model := entry.Model
			if !strings.Contains(model, "/") {
				switch entry.Provider {
				case "openai", "anthropic", "gemini":
					model = entry.Provider + "/" + model
				case "openai-compatible", "custom":
					model = "openai/" + model
				}
			}
			params := map[string]any{"model": model}
			if entry.BaseURL != "" {
				params["api_base"] = entry.BaseURL
			}
			if entry.CredentialID != "" {
				if secrets == nil {
					return fmt.Errorf("model %q references a credential but the encrypted vault is unavailable", entry.ID)
				}
				secret, err := secrets.Secret(ctx, entry.CredentialID)
				if err != nil {
					return fmt.Errorf("model %q credential %q is not configured", entry.ID, entry.CredentialID)
				}
				params["api_key"] = secret
			}
			modelList = append(modelList, map[string]any{
				"model_name":     entry.ID,
				"litellm_params": params,
			})
		}
	}

	config := map[string]any{
		"model_list": modelList,
		"general_settings": map[string]any{
			"master_key": "os.environ/LITELLM_MASTER_KEY",
		},
		"litellm_settings": map[string]any{
			"drop_params":     true,
			"request_timeout": 600,
		},
	}
	raw, err := yaml.Marshal(config)
	if err != nil {
		return err
	}
	header := "# Sovereign Gateway (LiteLLM) configuration — generated by Sovereign Control.\n# Do not hand-edit; regenerate via POST /api/control/v1/gateway/config/regenerate.\n"
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("gateway config directory: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".config-*.yaml")
	if err != nil {
		return fmt.Errorf("gateway config: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(append([]byte(header), raw...)); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("gateway config: %w", err)
	}
	return nil
}
