package gateway

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lazarus-AI-Research/sovereign-stack/control/internal/embeddings"
	"github.com/Lazarus-AI-Research/sovereign-stack/control/internal/models"
)

// BYOKKeyID is the credential vault entry holding SovereignGateway's
// secret-at-rest key: a 32-byte AES-256-GCM key, hex or base64.
//
// Without it the gateway stores every upstream provider key in plaintext, which
// would regress the encrypted provider credentials the product already ships.
const BYOKKeyID = "gateway-byok-key"

// GenerateConfig writes gateway.toml and syncs the model list over the admin
// API (§2.2: generated configuration; the gateway UI is never exposed).
//
// This splits in two because SovereignGateway does:
//   - process settings (bind, database, security, features) live in the TOML
//     file, which the gateway reads once at start;
//   - models live in its database, and are pushed to /admin/v1/models, where
//     the router hot-reloads them with no restart.
//
// So a model change costs nothing here, unlike LiteLLM's regenerate-and-restart.
// A change to the file itself still needs a restart, which NeedsReload reports.
func (c *Sovereign) GenerateConfig(ctx context.Context, path string, modelRegistry *models.Registry, profiles *embeddings.Registry, secrets SecretResolver) error {
	if err := c.writeServeConfig(ctx, path, secrets); err != nil {
		return err
	}
	return c.syncModels(ctx, modelRegistry, profiles, secrets)
}

// NeedsReload is false: the model list — the only part that changes in normal
// operation — is pushed over the admin API and hot-reloads.
func (c *Sovereign) NeedsReload() bool { return false }

// writeServeConfig renders the process settings.
func (c *Sovereign) writeServeConfig(ctx context.Context, path string, secrets SecretResolver) error {
	byok, err := byokKey(ctx, secrets)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("# Sovereign Gateway configuration — generated by Sovereign Control.\n")
	b.WriteString("# Do not hand-edit; regenerate via POST /api/control/v1/gateway/config/regenerate.\n")
	b.WriteString("#\n")
	b.WriteString("# Models are NOT here: they live in the gateway's database and are pushed\n")
	b.WriteString("# over /admin/v1/models, where the router hot-reloads them.\n\n")

	b.WriteString("[server]\n")
	b.WriteString(fmt.Sprintf("bind = %q\n", "0.0.0.0:8080"))
	b.WriteString("deployment_mode = \"selfhosted\"\n\n")

	b.WriteString("[database]\n")
	b.WriteString("backend = \"postgres\"\n")
	b.WriteString(fmt.Sprintf("dsn = %q\n\n", os.Getenv("SOVEREIGN_GATEWAY_DSN")))

	b.WriteString("[security]\n")
	// Without this the gateway keeps upstream provider keys in plaintext.
	b.WriteString(fmt.Sprintf("byok_key = %q\n\n", byok))

	b.WriteString("[features]\n")
	// §2.2 requires budgets and rate limits; both default to off upstream.
	b.WriteString("budgets_enabled = true\n")
	b.WriteString("ratelimit_enabled = true\n\n")

	b.WriteString("[reqlog]\n")
	// §2.4: prompt/response content capture is off unless an administrator
	// deliberately enables it. The appliance build omits the reqlog feature
	// entirely, so true here would refuse to start.
	b.WriteString("enabled = false\n\n")

	b.WriteString("[upstream]\n")
	b.WriteString("mode = \"http\"\n\n")

	b.WriteString("[routing]\n")
	b.WriteString("strategy = \"simple\"\n")

	return writeFileAtomic(path, []byte(b.String()))
}

// byokKey resolves the secret-at-rest key from the vault.
//
// Absence is an error, not a warning: proceeding would silently write every
// upstream provider key to disk in the clear.
func byokKey(ctx context.Context, secrets SecretResolver) (string, error) {
	if secrets == nil {
		return "", fmt.Errorf("the encrypted vault is unavailable, so %s cannot be resolved; "+
			"without it sovereign-gateway stores provider keys in plaintext", BYOKKeyID)
	}
	key, err := secrets.Secret(ctx, BYOKKeyID)
	if err != nil || key == "" {
		return "", fmt.Errorf("credential %q is not configured; without it sovereign-gateway "+
			"stores provider keys in plaintext (generate a 32-byte key and store it)", BYOKKeyID)
	}
	return key, nil
}

// syncModels reconciles the gateway's deployments with the product registries.
//
// Every stable alias — the generation model and each embedding profile's served
// name — routes to the single runtime endpoint; remote models keep their
// registry-declared routes. Deployments the product no longer declares are
// removed, so a deleted model stops being routable.
func (c *Sovereign) syncModels(ctx context.Context, modelRegistry *models.Registry, profiles *embeddings.Registry, secrets SecretResolver) error {
	desired, err := desiredDeployments(ctx, modelRegistry, profiles, secrets)
	if err != nil {
		return err
	}
	return c.reconcile(ctx, desired)
}

// reconcile makes the gateway's deployment list match desired: add what is
// missing, remove what the product no longer declares, leave the rest alone.
func (c *Sovereign) reconcile(ctx context.Context, desired []map[string]any) error {
	var existing []sovereignDeployment
	if err := c.do(ctx, http.MethodGet, "/admin/v1/models", nil, &existing); err != nil {
		return fmt.Errorf("list gateway models: %w", err)
	}
	have := map[string]sovereignDeployment{}
	for _, d := range existing {
		have[d.ModelName] = d
	}

	for _, d := range desired {
		if _, ok := have[d["model_name"].(string)]; ok {
			delete(have, d["model_name"].(string))
			continue
		}
		if err := c.do(ctx, http.MethodPost, "/admin/v1/models", d, nil); err != nil {
			return fmt.Errorf("add gateway model %v: %w", d["model_name"], err)
		}
	}
	// Whatever the product no longer declares.
	for name, d := range have {
		if err := c.do(ctx, http.MethodDelete, "/admin/v1/models/"+d.ID, nil, nil); err != nil {
			return fmt.Errorf("remove stale gateway model %q: %w", name, err)
		}
	}
	return nil
}

type sovereignDeployment struct {
	ID        string `json:"id"`
	ModelName string `json:"model_name"`
	Provider  string `json:"provider"`
}

// desiredDeployments is the deployment set the product's registries imply.
func desiredDeployments(ctx context.Context, modelRegistry *models.Registry, profiles *embeddings.Registry, secrets SecretResolver) ([]map[string]any, error) {
	entries, err := modelRegistry.List()
	if err != nil {
		return nil, err
	}
	profileMap, err := profiles.List()
	if err != nil {
		return nil, err
	}

	seen := map[string]bool{}
	var out []map[string]any

	// The local runtime speaks OpenAI's dialect for both roles.
	addRuntime := func(alias string, embed bool) {
		if alias == "" || seen[alias] {
			return
		}
		seen[alias] = true
		format := "openai_chat"
		if embed {
			format = "openai_embed"
		}
		out = append(out, map[string]any{
			"model_name":      alias,
			"provider":        "custom",
			"upstream_model":  alias,
			"upstream_format": format,
			"api_base":        "http://sovereign-runtime:8000/v1",
			"api_key":         os.Getenv("SOVEREIGN_RUNTIME_API_KEY"),
			"weight":          1,
		})
	}
	addRuntime("assistant-large", false)
	for _, profile := range profileMap {
		addRuntime(profile.ServedModelName, true)
	}

	for _, entry := range entries {
		if entry.Source != "remote" && entry.Source != "cloud" {
			continue
		}
		if seen[entry.ID] {
			continue
		}
		seen[entry.ID] = true

		format, err := upstreamFormat(entry.Provider)
		if err != nil {
			return nil, fmt.Errorf("model %q: %w", entry.ID, err)
		}
		d := map[string]any{
			"model_name":      entry.ID,
			"provider":        entry.Provider,
			"upstream_model":  entry.Model,
			"upstream_format": format,
			"weight":          1,
		}
		if entry.BaseURL != "" {
			d["api_base"] = entry.BaseURL
		}
		if entry.CredentialID != "" {
			if secrets == nil {
				return nil, fmt.Errorf("model %q references a credential but the encrypted vault is unavailable", entry.ID)
			}
			secret, err := secrets.Secret(ctx, entry.CredentialID)
			if err != nil {
				return nil, fmt.Errorf("model %q credential %q is not configured", entry.ID, entry.CredentialID)
			}
			d["api_key"] = secret
		}
		out = append(out, d)
	}
	return out, nil
}

// upstreamFormat maps a registry provider onto the gateway's adapter shape.
//
// An unknown provider is an error rather than a guess: picking the wrong dialect
// fails later, at request time, with a much worse error.
func upstreamFormat(provider string) (string, error) {
	switch provider {
	case "anthropic":
		return "anthropic", nil
	case "openai", "openai-compatible", "custom", "":
		return "openai_chat", nil
	case "gemini":
		return "gemini", nil
	default:
		return "", fmt.Errorf("provider %q has no sovereign-gateway adapter (want anthropic, openai, openai-compatible, custom, or gemini)", provider)
	}
}

// writeFileAtomic writes via a temp file and rename, 0600, so a reader never
// sees a half-written config.
func writeFileAtomic(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("gateway config directory: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".config-*.toml")
	if err != nil {
		return fmt.Errorf("gateway config: %w", err)
	}
	name := tmp.Name()
	defer os.Remove(name)
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(name, path); err != nil {
		return fmt.Errorf("gateway config: %w", err)
	}
	return nil
}
