#!/usr/bin/env bash
# Render a complete, owner-only appliance environment without prompting.
set -Eeuo pipefail

SOVEREIGN_HOME="${SOVEREIGN_HOME:-$HOME/.sovereign}"
PROFILE="${SOVEREIGN_PROFILE:-}"
VERSION="${SOVEREIGN_VERSION:-0.1.0-rc.3}"
RELEASE_ROOT="${SOVEREIGN_RELEASE_ROOT:-$SOVEREIGN_HOME/current}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --home) SOVEREIGN_HOME="$2"; shift 2 ;;
    --profile) PROFILE="$2"; shift 2 ;;
    --version) VERSION="${2#v}"; shift 2 ;;
    --release-root) RELEASE_ROOT="$2"; shift 2 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

[[ "$PROFILE" == "cuda-x86_64" || "$PROFILE" == "metal-arm64" ]] || {
  echo "error: --profile must be cuda-x86_64 or metal-arm64" >&2
  exit 2
}

umask 077
mkdir -p "$SOVEREIGN_HOME/secrets/litellm" "$SOVEREIGN_HOME/logs" \
  "$SOVEREIGN_HOME/reports" "$SOVEREIGN_HOME/backups" "$SOVEREIGN_HOME/bundles" \
  "$SOVEREIGN_HOME/models" "$SOVEREIGN_HOME/state"

ENV_FILE="$SOVEREIGN_HOME/.env"
existing() {
  local key="$1"
  [[ -f "$ENV_FILE" ]] || return 0
  sed -n "s/^${key}=//p" "$ENV_FILE" | tail -n 1
}
random_hex() { openssl rand -hex "$1"; }
keep_or_generate() {
  local key="$1" bytes="$2" value
  value="$(existing "$key")"
  [[ -n "$value" && "$value" != change-me* ]] || value="$(random_hex "$bytes")"
  printf '%s' "$value"
}

POSTGRES_PASSWORD="$(keep_or_generate POSTGRES_PASSWORD 24)"
LITELLM_MASTER_KEY="$(existing LITELLM_MASTER_KEY)"
[[ -n "$LITELLM_MASTER_KEY" && "$LITELLM_MASTER_KEY" != sk-change-me* ]] || LITELLM_MASTER_KEY="sk-$(random_hex 24)"
RUNTIME_KEY="$(keep_or_generate SOVEREIGN_RUNTIME_API_KEY 32)"
PROXY_TOKEN="$(keep_or_generate DOCKER_PROXY_TOKEN 32)"
INDEX_TOKEN="$(keep_or_generate WORKSPACE_INDEX_ADMIN_TOKEN 32)"
ADMIN_PASSWORD="$(keep_or_generate SOVEREIGN_ADMIN_PASSWORD 20)"

AGENT_TOKEN_FILE="$SOVEREIGN_HOME/agent.token"
if [[ ! -f "$AGENT_TOKEN_FILE" ]]; then
  random_hex 32 > "$AGENT_TOKEN_FILE"
fi
chmod 600 "$AGENT_TOKEN_FILE"
AGENT_TOKEN="$(<"$AGENT_TOKEN_FILE")"

VAULT_KEY_FILE="$SOVEREIGN_HOME/secrets/control-vault.key"
if [[ ! -f "$VAULT_KEY_FILE" ]]; then
  random_hex 32 > "$VAULT_KEY_FILE"
fi
chmod 600 "$VAULT_KEY_FILE"

CONTROL_IMAGE="ghcr.io/lazarus-ai-research/sovereign-control:$VERSION"
DOCKER_PROXY_IMAGE="ghcr.io/lazarus-ai-research/sovereign-docker-proxy:$VERSION"
EVALS_IMAGE="ghcr.io/lazarus-ai-research/sovereign-evals:$VERSION"
WORKSPACE_IMAGE="ghcr.io/lazarus-ai-research/sovereign-workspace:$VERSION"
if [[ "$PROFILE" == "metal-arm64" ]]; then
  EMBEDDING_ALIAS="embedding-text-compact"
  PASSAGE_PREFIX="search_document: "
  QUERY_PREFIX="search_query: "
  RUNTIME_IMAGE="ghcr.io/lazarus-ai-research/sovereign-runtime:metal-arm64-$VERSION"
else
  EMBEDDING_ALIAS="embedding-omni-default"
  PASSAGE_PREFIX=""
  QUERY_PREFIX=""
  RUNTIME_IMAGE="ghcr.io/lazarus-ai-research/sovereign-runtime:cuda-x86_64-$VERSION"
fi

MANIFEST_FILE="$RELEASE_ROOT/release/manifest.json"
IMAGE_LOCK_FILE="$RELEASE_ROOT/release/images.env"
locked_image() {
  local key="$1" expected="$2" value digest
  value="$(sed -n "s/^${key}=//p" "$IMAGE_LOCK_FILE" | tail -n 1)"
  [[ "$value" == "$expected@sha256:"* ]] || {
    echo "error: $key is missing or inconsistent with release $VERSION" >&2
    return 1
  }
  digest="${value##*@sha256:}"
  [[ ${#digest} -eq 64 && "$digest" != *[!0-9a-f]* ]] || {
    echo "error: $key has an invalid digest" >&2
    return 1
  }
  printf '%s' "$value"
}
if [[ -f "$MANIFEST_FILE" ]]; then
  [[ -f "$IMAGE_LOCK_FILE" ]] || {
    echo "error: signed release manifest has no image lock" >&2
    exit 1
  }
  CONTROL_IMAGE="$(locked_image SOVEREIGN_CONTROL_IMAGE "$CONTROL_IMAGE")"
  DOCKER_PROXY_IMAGE="$(locked_image SOVEREIGN_DOCKER_PROXY_IMAGE "$DOCKER_PROXY_IMAGE")"
  EVALS_IMAGE="$(locked_image SOVEREIGN_EVALS_IMAGE "$EVALS_IMAGE")"
  WORKSPACE_IMAGE="$(locked_image SOVEREIGN_WORKSPACE_IMAGE "$WORKSPACE_IMAGE")"
  if [[ "$PROFILE" == "metal-arm64" ]]; then
    RUNTIME_IMAGE="$(locked_image SOVEREIGN_RUNTIME_METAL_IMAGE "$RUNTIME_IMAGE")"
  else
    RUNTIME_IMAGE="$(locked_image SOVEREIGN_RUNTIME_CUDA_IMAGE "$RUNTIME_IMAGE")"
  fi
fi

TMP="$ENV_FILE.tmp.$$"
cat > "$TMP" <<EOF
# Generated by SovereignStack $VERSION. Owner-readable only.
SOVEREIGN_VERSION=$VERSION
SOVEREIGN_PROFILE=$PROFILE
SOVEREIGN_RELEASE_ROOT=$RELEASE_ROOT
SOVEREIGN_BIND_ADDRESS=127.0.0.1
SOVEREIGN_HOST_UID=$(id -u)
SOVEREIGN_HOST_GID=$(id -g)
HTTP_PORT=${SOVEREIGN_HTTP_PORT:-8880}

SOVEREIGN_CONTROL_IMAGE=$CONTROL_IMAGE
SOVEREIGN_DOCKER_PROXY_IMAGE=$DOCKER_PROXY_IMAGE
SOVEREIGN_EVALS_IMAGE=$EVALS_IMAGE
SOVEREIGN_WORKSPACE_IMAGE=$WORKSPACE_IMAGE
SOVEREIGN_RUNTIME_IMAGE=$RUNTIME_IMAGE

CADDY_IMAGE=caddy@sha256:af5fdcd76f2db5e4e974ee92f96ee8c0fc3edb55bd4ba5032547cbf3f65e486d
LITELLM_IMAGE=ghcr.io/berriai/litellm@sha256:f46d672e9d12a84e5dde046ff3865e0bf323e49f9f9b8eb08cd33c1713ea9627
PGVECTOR_IMAGE=pgvector/pgvector@sha256:1d533553fefe4f12e5d80c7b80622ba0c382abb5758856f52983d8789179f0fb
PHOENIX_IMAGE=arizephoenix/phoenix@sha256:0826e5c6247d012bf8cfb58df5dd9778b26ebb7f9b1afac577a8e0bb3d83606f
PROMETHEUS_IMAGE=prom/prometheus@sha256:3c42b892cf723fa54d2f262c37a0e1f80aa8c8ddb1da7b9b0df9455a35a7f893
GRAFANA_IMAGE=grafana/grafana@sha256:121a7a9ece6dc10b969f1f96eed64b4f07dfac0d0b8abc070f7cb83bbde86f63
LOKI_IMAGE=grafana/loki@sha256:70b9f699fc9bb868b62f1cfd4f787dfa50242f1fd92e6089787d5d7daea75fe8
OTEL_IMAGE=otel/opentelemetry-collector-contrib@sha256:125bdbeb7590cc1952c5b3430ecf14063568980c2c93d5b38676cc0446ed8108

STORAGE_DIR=/app/server/storage
DISABLE_TELEMETRY=true
LLM_PROVIDER=generic-openai
GENERIC_OPEN_AI_BASE_PATH=http://sovereign-gateway:4000/v1
GENERIC_OPEN_AI_API_KEY=$LITELLM_MASTER_KEY
GENERIC_OPEN_AI_MODEL_PREF=assistant-large
GENERIC_OPEN_AI_MODEL_TOKEN_LIMIT=2048
EMBEDDING_ENGINE=generic-openai
EMBEDDING_BASE_PATH=http://sovereign-gateway:4000/v1
GENERIC_OPEN_AI_EMBEDDING_API_KEY=$LITELLM_MASTER_KEY
EMBEDDING_MODEL_PREF=$EMBEDDING_ALIAS
GENERIC_OPEN_AI_EMBEDDING_PASSAGE_PREFIX="$PASSAGE_PREFIX"
GENERIC_OPEN_AI_EMBEDDING_QUERY_PREFIX="$QUERY_PREFIX"
VECTOR_DB=pgvector
PGVECTOR_CONNECTION_STRING=postgresql://sovereign:$POSTGRES_PASSWORD@postgres:5432/vectors

POSTGRES_USER=sovereign
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
CONTROL_DATABASE_URL=postgres://sovereign:$POSTGRES_PASSWORD@postgres:5432/sovereign_control?sslmode=disable
DATABASE_URL=postgres://sovereign:$POSTGRES_PASSWORD@postgres:5432/litellm
PHOENIX_SQL_DATABASE_URL=postgresql://sovereign:$POSTGRES_PASSWORD@postgres:5432/phoenix
LITELLM_MASTER_KEY=$LITELLM_MASTER_KEY
SOVEREIGN_ADMIN_PASSWORD=$ADMIN_PASSWORD
SOVEREIGN_RUNTIME_API_KEY=$RUNTIME_KEY
DOCKER_PROXY_TOKEN=$PROXY_TOKEN
WORKSPACE_INDEX_ADMIN_TOKEN=$INDEX_TOKEN
SOVEREIGN_AGENT_TOKEN=$AGENT_TOKEN
SOVEREIGN_VAULT_KEY_FILE=/sovereign/secrets/control-vault.key
RUNTIME_CONFIG_PATH=/sovereign/config/runtime.yaml
LITELLM_CONFIG_PATH=/sovereign/secrets/litellm/config.yaml
LITELLM_CONFIG_HOST_PATH=./secrets/litellm/config.yaml
DEPLOY_ROOT=$SOVEREIGN_HOME
HF_TOKEN=${HF_TOKEN:-$(existing HF_TOKEN)}
HF_HOME=/models/hf
EOF
chmod 600 "$TMP"
mv "$TMP" "$ENV_FILE"

printf '%s\n' "$PROFILE" > "$SOVEREIGN_HOME/state/profile"
chmod 600 "$SOVEREIGN_HOME/state/profile"

CREDENTIALS="$SOVEREIGN_HOME/credentials"
cat > "$CREDENTIALS" <<EOF
username=admin
password=$ADMIN_PASSWORD
url=http://127.0.0.1:${SOVEREIGN_HTTP_PORT:-8880}/control/
EOF
chmod 600 "$CREDENTIALS"

GATEWAY_CONFIG="$SOVEREIGN_HOME/secrets/litellm/config.yaml"
if [[ ! -s "$GATEWAY_CONFIG" ]]; then
  cp "$RELEASE_ROOT/deploy/config/litellm/config.yaml" "$GATEWAY_CONFIG"
  chmod 600 "$GATEWAY_CONFIG"
fi

echo "generated $ENV_FILE for $PROFILE"
